### PR TITLE
fix: options formatter for manpages

### PR DESCRIPTION
**Pull request by fmoessbauer**
The "options" formatter for the manpage generation did not output any option, as the loop used a wrong key in the parser_info dictionary (likely a typo).

This patch fixes this, which results in correctly printed parser options in manpage mode.

### CODE REVIEW

**Comment by fmoessbauer** [comment]
The CI failure is unrelated.

**Comment by ashb** [comment]
Please add tests

**Comment by fmoessbauer** [comment]
> Please add tests

The whole man page generation is not tested (yet). Unfortunately I don't have the time to start this from scratch. If others are interested, I'm happy to review, though. My fix is a minimal drive-by fix while checking why many sphinx-generated manpages lack the parser options entries (found while working on https://github.com/siemens/kas/commit/3f468481332e75db562d2939719f671b76590e2e).

**Comment by ashb** [comment]
> > Please add tests
> 
> The whole man page generation is not tested (yet). Unfortunately I don't have the time to start this from scratch. If others are interested, I'm happy to review, though. My fix is a minimal drive-by fix while checking why many sphinx-generated manpages lack the parser options entries (found while working on https://github.com/siemens/kas/commit/3f468481332e75db562d2939719f671b76590e2e).

Ack.

**Review by ashb — APPROVED** [review]

**Pull request merged**
